### PR TITLE
special hack for extension of 'anyType'

### PR DESCRIPTION
**Pull request by zuckschwerdt**
This special case is needed to allow types to be an extension on `anyType`. (used to introduce attributes on general container types).  E.g.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">

    <element name="container">
        <complexType>
            <complexContent>
                <extension base="anyType">
                    <sequence>
                        <!-- here we need to synthesize something like this:
                              any minOccurs="0" maxOccurs="unbounded"/-->
                        <element name="comment" type="string" />
                    </sequence>
                    <attribute name="color" type="string" />
                </extension>
            </complexContent>
        </complexType>
    </element>

    <!-- this would be in another xsd -->
    <element name="item">
        <complexType>
            <simpleContent>
                <extension base="string">
                    <attribute name="type" type="string" />
                </extension>
            </simpleContent>
        </complexType>
    </element>

</schema>
```

with a sample document of

```
<container>
<item type="test">foo</item>
<item type="empty" />
<comment>hi</comment>
Mixed
</container>'
```

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Actually an extension of anyType should provide an element (or sequence) of anyType to accept unspecified complex content. This needs more thought…

**Comment by willemdj** [comment]
Hi,

I tested your other changes against my test set and pulled them.The status of this one is not clear to me - does it solve your problem? Should I pull it?

Regards,
Willem

**Comment by zuckschwerdt** [comment]
Thanks! Let me think about this patch some more. For now, don't merge.
This patch helps to parse my XSD but the model then won't do. (I need it to allow random elements into that type in XML) Currently I need to hack the type to allow some elements and that way I won't need the extension=anyType. Not useful in any way, I guess.

**Comment by zuckschwerdt** [comment]
The patch now works. As per XSD specs a type that derives by means of `extension base="anyType"` now allows arbitrary content. I.e. an AnyType is inserted with `lax` processing and `mixed` content.

**Comment by willemdj** [comment]
Hi,

When testing this I ran into a problem. I don't have much time right now, but I have the impression that the problem is actually not in this change, but in #40 - probably I didn't pay enough attention when running my tests at that time.

The XSD I am testing:

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="items" type="ItemsType"/>

  <xs:complexType name="ItemsType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="hat" type="ProductType"/>
      <xs:element name="umbrella" type="RestrictedProductType"/>
      <xs:element name="shirt" type="ShirtType"/>
    </xs:choice>
  </xs:complexType>

  
  <xs:complexType name="ItemType" abstract="true">
    <xs:attribute name="routingNum" type="xs:integer"/>
  </xs:complexType>

  
  <xs:complexType name="ProductType">
    <xs:complexContent>
      <xs:extension base="ItemType">
        <xs:sequence>
          <xs:element name="number" type="xs:integer"/>
          <xs:element name="name" type="xs:string"/>
          <xs:element name="description"
                       type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="effDate" type="xs:date"/>
        <xs:attribute name="lang" type="xs:language"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  
  <xs:complexType name="RestrictedProductType">
    <xs:complexContent>
      <xs:restriction base="ProductType">
        <xs:sequence>
          <xs:element name="number" type="xs:integer"/>
          <xs:element name="name" type="xs:token"/>
        </xs:sequence>
        <xs:attribute name="routingNum"
                       type="xs:short" use="required"/>
        <xs:attribute name="effDate"
                       type="xs:date" default="1900-01-01"/>
        <xs:attribute name="lang" use="prohibited"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  
  <xs:complexType name="ShirtType">
    <xs:complexContent>
      <xs:extension base="RestrictedProductType">
        <xs:choice maxOccurs="unbounded">
          <xs:element name="size" type="SmallSizeType"/>
          <xs:element name="color" type="ColorType"/>
        </xs:choice>
        <xs:attribute name="sleeve" type="xs:integer"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  
  <xs:complexType name="SizeType">
    <xs:simpleContent>
      <xs:extension base="xs:integer">
        <xs:attribute name="system" type="xs:token"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  
  <xs:complexType name="SmallSizeType">
    <xs:simpleContent>
      <xs:restriction base="SizeType">
        <xs:minInclusive value="2"/>
        <xs:maxInclusive value="6"/>
        <xs:attribute  name="system" type="xs:token"
                        use="required"/>
      </xs:restriction>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="ColorType">
    <xs:attribute name="value" type="xs:string"/>
  </xs:complexType>

</xs:schema>

The XML:
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="chapter14.xsd">
  <hat routingNum="123456" effDate="2002-04-02" lang="en-US">
    <number>557</number>
    <name>Ten-Gallon Hat</name>
    <description>This is a great hat!</description>
  </hat>
  <umbrella routingNum="123" effDate="2002-04-02">
    <number>557</number>
    <name>Ten-Gallon Hat</name>
  </umbrella>
  <shirt routingNum="124" effDate="2002-04-02" sleeve="17">
    <number>557</number>
    <name>Short-Sleeved Linen Blouse</name>
    <color value="blue"/>
    <size system="US-DRESS">6</size>
  </shirt>
</items>

This gives an error like this:
[{exception,{error,"Unexpected attribute: sleeve"}},
              {stack,['t#ItemsType']},
              {received,
                  {startElement,[],"shirt",[],
                      [{attribute,"sleeve",[],[],"17"},
                       {attribute,"effDate",[],[],"2002-04-02"},
                       {attribute,"routingNum",[],[],"124"}]}}]

**Comment by zuckschwerdt** [comment]
I'll sort this out. Can you edit your comment and put the code in tripple backticks?

**Comment by willemdj** [comment]
I added the backticks. Looks much better that way.

**Comment by zuckschwerdt** [comment]
There is a hidden bug that was exposed by #40.
The schema type hierachy here is (top-down):
`ShirtType` extends `RestrictedProductType` restricts `ProductType` extends `ItemType`

Previously the `translateType/3` recursion stopped at `RestrictedProductType` because the restriction was ignored.
Per chance this yielded a working model with attributes from `ShirtType` appended to attributes from `RestrictedProductType`.
Coincidentally there is no overlap in the attributes here and the model looks fine. Given some overlap in attributes, say `ShirtType` declaring `effDate` as `required`, the model would break with that attribute doubly defined.

Also the attributes from the base types referred through the `restriction` are lost. Say `ItemType` had an attribute named `weight`, that would not appear in the model. This was fixed by #40.

The problem actually is with simply appending attributes as in `attributes = BaseAttrs ++ Attrs`. The proper way would be to merge the attributes with precedence to the derived type's. A proposed fix is in #46.

**Pull request merged**
