### PR TITLE
Type hierarchy lookup for types with no prefixes fixed.

### PR DESCRIPTION
**Pull request by kape1395**

### CODE REVIEW

**Comment by willemdj** [comment]
Hi Karolis,

Can you give an example of a situation where this change is needed? So that I can test it.

Regards,
Willem

**Comment by kape1395** [comment]
I have no small example of it right now (my generated hrl is of 72kloc).
I will try to add a test case next week for it. A minimal XSD/XML will be included.
Do not merge this for now.

**Comment by willemdj** [comment]
Ok, great, thanks.

Op wo 1 aug. 2018 om 15:33 schreef Karolis Petrauskas <
notifications@github.com>:

**Comment by kape1395** [comment]
I added the test case and some comments. The problem appears only in the cases, when the default namespace is specified explicitly.

**Comment by willemdj** [comment]
Pulled, thanks.

**Pull request merged**
