### PR TITLE
The simpleType add final attribute

### PR DESCRIPTION
**Pull request by cisiqo**
The simpleType add final attribute

### CODE REVIEW

**Comment by willemdj** [comment]
Hi, sorry that I did not respond to this. Did you close it because you concluded that it was not correct or not needed? Or is it still relevant?

**Comment by cisiqo** [comment]
THANKS FOR YOUR REPLY. I'm a newbee, i use the function `write_xsd_hrl_file/3` with the https://www.ecma-international.org/publications-and-standards/standards/ecma-376/ , have something wrong with `final` attribute. i push the first commit it worked for me. I think it cottect.

Then found the function write hrl file repect some record and type, other erl file include it will throw an error. I haven't verified it, so I accidentally committed it.

So sorry.

**Comment by willemdj** [comment]
Ok, I merged your solution for the "final" attribute, thanks.

**Comment by cisiqo** [comment]
Awesome thank you so much.

**Pull request closed without merging**
